services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: ${ACR_LOGIN_SERVER}/frontend:${CI_COMMIT_REF_SLUG}
    container_name: goal-tracker-frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - goal-tracker-network
    restart: unless-stopped


  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: ${ACR_LOGIN_SERVER}/backend:${CI_COMMIT_REF_SLUG}
    container_name: goal-tracker-backend
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=goalsdb
      - SSL=disable
      - PORT=8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - goal-tracker-network
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: goal-tracker-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=goalsdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - goal-tracker-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  goal-tracker-network:
    driver: bridge

volumes:
  postgres-data:
  node_modules:
