workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

stages:
  - validate
  - plan
  - apply

default:
  image:
    name: hashicorp/terraform:latest
    entrypoint:
      - /usr/bin/env
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

  before_script:
    - cd terrform-vm
    - terraform init

  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - terrform-vm/.terraform/

terraform_validate:
  stage: validate
  script:
    - terraform validate

terraform_plan:
  stage: plan
  script: 
    - terraform plan -out=tfplan 
  artifacts:
    name: "terraform-plan-$CI_COMMIT_REF_NAME"
    paths:
      - terrform-vm/tfplan

terraform_apply:
  stage: apply
  dependencies:
    - terraform_plan
  script:
    - terraform apply --auto-approve tfplan
  when: manual
  allow_failure: false
  only:
    refs:
      - main
